import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';

import 'app.dart';
import 'core/services/firestore_service.dart';
// import 'firebase_options.dart'; // generated by `flutterfire configure`

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    // options: DefaultFirebaseOptions.currentPlatform,
  );

  // Must be set before any Firestore read/write happens.
  FirestoreService.enableOfflinePersistence();

  runApp(
    const ProviderScope(
      child: WholesaleErpApp(),
    ),
  );
}
